name: "Publish to GitHub Pages"

env:
  GODOT_VERSION: 4.3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Build Frontend and Deploy to Github Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p frontend/build/web

      - name: Build
        run: godot -v --export-debug --headless "Web" ../frontend/build/web/index.html frontend/project/project.godot

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js frontend/build/web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' frontend/build/web/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
  
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move Linux templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p backend/build/linux
      
        - name: Build
        run: godot -v --export-debug --headless "Linux" ../backend/build/linux/frogger_backend.x86_64 backend/project/project.godot

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: backend/build/linux